### PR TITLE
Added ZipCode Service and Tests

### LINKED ISSUE #16: Add Zipcode Service and Tests
# Acceptance Criteria:

- [ ] There is <tt>ZipcodeQueryService.java</tt> file in the `src/main/java/edu/ucsb/cs156/spring/backend/services` directory.
- [ ] <tt>ZipcodeQueryService.java</tt>  implements a class that make a call to the appropriate API
      and returns the results.
- [ ] There is  <tt>ZipcodeQueryServiceTests.java</tt> file in the `src/test/java/edu/ucsb/cs156/spring/backend/services` directory.
- [ ] The tests in  <tt>ZipcodeQueryServiceTests.java</tt> provide 100% coverage of  <tt>ZipcodeQueryService.java</tt> for both jacoco and pitest.
      
# Details

See the assignment description at https://ucsb-cs156.github.io/f23/lab/team01 for details.

### PR DESCRIPTION
**Pull request by Joseph-Foster**
In this PR, we add a service that wraps the ZipCode API from 
http://api.zippopotam.us/us/{zipcode}

Closes #16

### CODE REVIEW

**Review by jakedel — CHANGES_REQUESTED** [review]
Didn't pass the 13-backend-incremental-pitest check, please fix before we can merge this

**Comment by Joseph-Foster** [comment]
All my local tests are passing, and as far as I can tell there are no bugs. Not sure what else to do.

**Comment by Joseph-Foster** [comment]
Removing Object Mapper fixed it, not sure why. It had been in the Country Code example.

**Review by jakedel — APPROVED** [review]
LGTM

**Pull request merged**
